### ISSUE TITLE
"File" value is always `null`

### ISSUE THREAD

**Issue by klokie** [olragon/graphql_api#5]
Hello, is there any way to retrieve the URLs of files attached to a node? All I get are `null` values, e.g.
```
"field_assets": [
              {
                "file": null,
                "description": ""
              }
            ],
```

This seems to be the case both for File fields (using [Media](https://www.drupal.org/project/Media)) and Image fields.

**Comment by olragon** [comment]
Fixed in https://github.com/olragon/graphql_api/commit/59bf8642f5c42477a6c5a37677e6f9539f5a03a3

- If you have mix files before and after enable [Media](http://drupal.org/project/media), please use module `media_migrate_file_types` to migrate old files.
- If you want to expose image field url with image styles, please implement hook `entity_property_info_alter` and add `styles` property

**Comment by klokie** [comment]
works great – thank you!
